### ISSUE TITLE
UML SoftOne Andersson Avila Rojas

### ISSUE THREAD

**Issue by AnderssonAvilaRojas** [LauraSilvaAyala/CuentasClaras#1]
![UML](https://user-images.githubusercontent.com/79039742/107889293-8f8bd380-6edf-11eb-85d7-322a77c76f28.png)

**Comment by LauraSilvaAyala** [comment]
??
________________________________
De: AnderssonAvilaRojas <notifications@github.com>
Enviado: domingo, 14 de febrero de 2021 16:14
Para: LauraSilvaAyala/CuentasClaras <CuentasClaras@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Asunto: [LauraSilvaAyala/CuentasClaras] UML SoftOne Andersson Avila Rojas (#1)


[UML]<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F79039742%2F107889293-8f8bd380-6edf-11eb-85d7-322a77c76f28.png&data=04%7C01%7C%7C0633515700b349ab691908d8d12d833a%7Cfabd047cff48492a8bbb8f98b9fb9cca%7C1%7C0%7C637489340696775984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XICVqT%2BpwqcSBLOfEzzWrktmykC%2FHzdt%2FZCID4meAKc%3D&reserved=0>
